sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -t ansible_xenial           ubuntu16.04
    - docker build  -t ansible_trusty           ubuntu14.04
    - docker build  -t ansible_precise          ubuntu12.04
    - docker build  -t ansible_jessie           debian8
    - docker build  -t ansible_wheezy           debian7
    - docker build  -t ansible_centos7          centos7
    - docker build  -t ansible_centos6          centos6
    - docker build  -t ansible_alpine3          alpine3

    - docker build  -t ansible_xenial_onbuild   ubuntu16.04-onbuild
    - docker build  -t ansible_trusty_onbuild   ubuntu14.04-onbuild
    - docker build  -t ansible_precise_onbuild  ubuntu12.04-onbuild
    - docker build  -t ansible_jessie_onbuild   debian8-onbuild
    - docker build  -t ansible_wheezy_onbuild   debian7-onbuild
    - docker build  -t ansible_centos7_onbuild  centos7-onbuild
    - docker build  -t ansible_centos6_onbuild  centos6-onbuild
    - docker build  -t ansible_alpine3_onbuild  alpine3-onbuild


    - docker build  -t ansible_1.9_trusty           1.9-ubuntu14.04
    - docker build  -t ansible_1.9_precise          1.9-ubuntu12.04
    - docker build  -t ansible_1.9_jessie           1.9-debian8
    - docker build  -t ansible_1.9_wheezy           1.9-debian7
    - docker build  -t ansible_1.9_centos7          1.9-centos7
    - docker build  -t ansible_1.9_centos6          1.9-centos6
    - docker build  -t ansible_1.9_alpine3          1.9-alpine3

    - docker build  -t ansible_1.9_trusty_onbuild   1.9-ubuntu14.04-onbuild
    - docker build  -t ansible_1.9_precise_onbuild  1.9-ubuntu12.04-onbuild
    - docker build  -t ansible_1.9_jessie_onbuild   1.9-debian8-onbuild
    - docker build  -t ansible_1.9_wheezy_onbuild   1.9-debian7-onbuild
    - docker build  -t ansible_1.9_centos7_onbuild  1.9-centos7-onbuild
    - docker build  -t ansible_1.9_centos6_onbuild  1.9-centos6-onbuild
    - docker build  -t ansible_1.9_alpine3_onbuild  1.9-alpine3-onbuild


    - docker build  -t ansible_master_xenial           master-ubuntu16.04
    - docker build  -t ansible_master_trusty           master-ubuntu14.04
    - docker build  -t ansible_master_precise          master-ubuntu12.04
    - docker build  -t ansible_master_jessie           master-debian8
    - docker build  -t ansible_master_wheezy           master-debian7
    - docker build  -t ansible_master_centos7          master-centos7
    - docker build  -t ansible_master_centos6          master-centos6

    - docker build  -t ansible_master_xenial_onbuild   master-ubuntu16.04-onbuild
    - docker build  -t ansible_master_trusty_onbuild   master-ubuntu14.04-onbuild
    - docker build  -t ansible_master_precise_onbuild  master-ubuntu12.04-onbuild
    - docker build  -t ansible_master_jessie_onbuild   master-debian8-onbuild
    - docker build  -t ansible_master_wheezy_onbuild   master-debian7-onbuild
    - docker build  -t ansible_master_centos7_onbuild  master-centos7-onbuild
    - docker build  -t ansible_master_centos6_onbuild  master-centos6-onbuild


    - docker build  -t ansible_mini_alpine3    mini-alpine3
    - docker build  -t ansible_mini_debian8    mini-debian8
    - docker build  -t nginx_alpine3   -f mini-test/Dockerfile.alpine3   mini-test
    - docker build  -t nginx_debian8   -f mini-test/Dockerfile.debian8   mini-test


script:
    - docker run -i ansible_xenial           > result-ubuntu16.04
    - docker run -i ansible_trusty           > result-ubuntu14.04
    - docker run -i ansible_precise          > result-ubuntu12.04
    - docker run -i ansible_jessie           > result-debian8
    - docker run -i ansible_wheezy           > result-debian7
    - docker run -i ansible_centos7          > result-centos7
    - docker run -i ansible_centos6          > result-centos6
    - docker run -i ansible_alpine3          > result-alpine3
    - docker run -i ansible_xenial_onbuild   > result-ubuntu16.04-onbuild
    - docker run -i ansible_trusty_onbuild   > result-ubuntu14.04-onbuild
    - docker run -i ansible_precise_onbuild  > result-ubuntu12.04-onbuild
    - docker run -i ansible_jessie_onbuild   > result-debian8-onbuild
    - docker run -i ansible_wheezy_onbuild   > result-debian7-onbuild
    - docker run -i ansible_centos7_onbuild  > result-centos7-onbuild
    - docker run -i ansible_centos6_onbuild  > result-centos6-onbuild
    - docker run -i ansible_alpine3_onbuild  > result-alpine3-onbuild


    - docker run -i ansible_1.9_trusty           > result-1.9-ubuntu14.04
    - docker run -i ansible_1.9_precise          > result-1.9-ubuntu12.04
    - docker run -i ansible_1.9_jessie           > result-1.9-debian8
    - docker run -i ansible_1.9_wheezy           > result-1.9-debian7
    - docker run -i ansible_1.9_centos7          > result-1.9-centos7
    - docker run -i ansible_1.9_centos6          > result-1.9-centos6
    - docker run -i ansible_1.9_alpine3          > result-1.9-alpine3
    - docker run -i ansible_1.9_trusty_onbuild   > result-1.9-ubuntu14.04-onbuild
    - docker run -i ansible_1.9_precise_onbuild  > result-1.9-ubuntu12.04-onbuild
    - docker run -i ansible_1.9_jessie_onbuild   > result-1.9-debian8-onbuild
    - docker run -i ansible_1.9_wheezy_onbuild   > result-1.9-debian7-onbuild
    - docker run -i ansible_1.9_centos7_onbuild  > result-1.9-centos7-onbuild
    - docker run -i ansible_1.9_centos6_onbuild  > result-1.9-centos6-onbuild
    - docker run -i ansible_1.9_alpine3_onbuild  > result-1.9-alpine3-onbuild


    - docker run -i ansible_master_xenial           > result-master-ubuntu16.04
    - docker run -i ansible_master_trusty           > result-master-ubuntu14.04
    - docker run -i ansible_master_precise          > result-master-ubuntu12.04
    - docker run -i ansible_master_jessie           > result-master-debian8
    - docker run -i ansible_master_wheezy           > result-master-debian7
    - docker run -i ansible_master_centos7          > result-master-centos7
    - docker run -i ansible_master_centos6          > result-master-centos6
    - docker run -i ansible_master_xenial_onbuild   > result-master-ubuntu16.04-onbuild
    - docker run -i ansible_master_trusty_onbuild   > result-master-ubuntu14.04-onbuild
    - docker run -i ansible_master_precise_onbuild  > result-master-ubuntu12.04-onbuild
    - docker run -i ansible_master_jessie_onbuild   > result-master-debian8-onbuild
    - docker run -i ansible_master_wheezy_onbuild   > result-master-debian7-onbuild
    - docker run -i ansible_master_centos7_onbuild  > result-master-centos7-onbuild
    - docker run -i ansible_master_centos6_onbuild  > result-master-centos6-onbuild


    - docker run -i nginx_alpine3  2> result-nginx-alpine3
    - docker run -i nginx_debian8  2> result-nginx-debian8


    - echo "==> Validating the test results..."
    - sh -c "[ -s result-ubuntu16.04         ]"
    - sh -c "[ -s result-ubuntu14.04         ]"
    - sh -c "[ -s result-ubuntu12.04         ]"
    - sh -c "[ -s result-debian8             ]"
    - sh -c "[ -s result-debian7             ]"
    - sh -c "[ -s result-centos7             ]"
    - sh -c "[ -s result-centos6             ]"
    - sh -c "[ -s result-alpine3             ]"
    - sh -c "[ -s result-ubuntu16.04-onbuild ]"
    - sh -c "[ -s result-ubuntu14.04-onbuild ]"
    - sh -c "[ -s result-ubuntu12.04-onbuild ]"
    - sh -c "[ -s result-debian8-onbuild     ]"
    - sh -c "[ -s result-debian7-onbuild     ]"
    - sh -c "[ -s result-centos7-onbuild     ]"
    - sh -c "[ -s result-centos6-onbuild     ]"
    - sh -c "[ -s result-alpine3-onbuild     ]"

    - sh -c "[ -s result-1.9-ubuntu14.04         ]"
    - sh -c "[ -s result-1.9-ubuntu12.04         ]"
    - sh -c "[ -s result-1.9-debian8             ]"
    - sh -c "[ -s result-1.9-debian7             ]"
    - sh -c "[ -s result-1.9-centos7             ]"
    - sh -c "[ -s result-1.9-centos6             ]"
    - sh -c "[ -s result-1.9-alpine3             ]"
    - sh -c "[ -s result-1.9-ubuntu14.04-onbuild ]"
    - sh -c "[ -s result-1.9-ubuntu12.04-onbuild ]"
    - sh -c "[ -s result-1.9-debian8-onbuild     ]"
    - sh -c "[ -s result-1.9-debian7-onbuild     ]"
    - sh -c "[ -s result-1.9-centos7-onbuild     ]"
    - sh -c "[ -s result-1.9-centos6-onbuild     ]"
    - sh -c "[ -s result-1.9-alpine3-onbuild     ]"

    - sh -c "[ -s result-master-ubuntu16.04         ]"
    - sh -c "[ -s result-master-ubuntu14.04         ]"
    - sh -c "[ -s result-master-ubuntu12.04         ]"
    - sh -c "[ -s result-master-debian8             ]"
    - sh -c "[ -s result-master-debian7             ]"
    - sh -c "[ -s result-master-centos7             ]"
    - sh -c "[ -s result-master-centos6             ]"
    - sh -c "[ -s result-master-ubuntu16.04-onbuild ]"
    - sh -c "[ -s result-master-ubuntu14.04-onbuild ]"
    - sh -c "[ -s result-master-ubuntu12.04-onbuild ]"
    - sh -c "[ -s result-master-debian8-onbuild     ]"
    - sh -c "[ -s result-master-debian7-onbuild     ]"
    - sh -c "[ -s result-master-centos7-onbuild     ]"
    - sh -c "[ -s result-master-centos6-onbuild     ]"

    - sh -c "[ -s result-nginx-alpine3     ]"
    - sh -c "[ -s result-nginx-debian8     ]"
